version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"  # Asegúrate de que este puerto esté disponible
    container_name: loan_management_system